### ISSUE TITLE
💄 Cosmetic issues

### ISSUE THREAD

**Issue by josephmiclaus** [fhstp-mfg/mobilot#105]
- [x] Move Duplicate to Settings
- [x] "New password" input under "Current password" input (see #101)
- [x] StationCreator EditorTools horizontal scroll dock right
- [x] Add missing `md-mobilot` class on raised and primary buttons

Moved:
- Fix MenuHeader height (see #114)

and many other ...

**Comment by doomsayer2** [comment]
Wow so far fantastic changes and great work. Is the scroll dock difficult or easy.

**Comment by josephmiclaus** [comment]
@doomsayer2 thanks ! 

it shouldn't be that hard ^^

**Comment by josephmiclaus** [comment]
Closing this for now, create individual styling and enhancement issues.
