### ISSUE TITLE
Add LaunchScreen for iOS

### ISSUE THREAD

**Issue by josephmiclaus** [fhstp-mfg/mobilot#116]

**Comment by josephmiclaus** [comment]
After native LaunchScreen, a white screen is shown.

use [cordova-plugin-splashscreen](https://www.npmjs.com/package/cordova-plugin-splashscreen)

**config.xml**

```
 <preference name="SplashScreenDelay" value="3000" />
<preference name="FadeSplashScreenDuration" value="750"/>
```

use `Splashscreen.hide()` when document has loaded

**Comment by doomsayer2** [comment]
Added functionallity, but needs to be tested. 
Generally, if the splashscreen should be hidden in code. It must be done in `deviceready()` event. There the following should be called `navigator.splashscreen.hide();`
