### ISSUE TITLE
Add JS bundler

### ISSUE THREAD

**Issue by josephmiclaus** [fhstp-mfg/mobilot#121]

**Comment by josephmiclaus** [comment]
@doomsayer2 @kblumenstein @abisz  

## Major Breaking Change
The app now requires bundling !

### Install dependencies
Run `npm install` to install new dependencies.

### Explanation
Commit 11f2061 includes a bundled `app.bundle.js` file in `angular.html`. This means that every change requires rebundling the app. I chose to do this with `gulp`, since it seemed the most convenient way and has little to no configuration effort. 

You can bundle the app by running the following from `public/`:
```
./node_modules/gulp/bin/gulp.js build
```

**Note** that currently the **uglify** pipe is commented out (ed053cc), since bundling takes around **22 seconds** with and only around **1.2 seconds** without uglifying.

### Improvements

- [x] Add `prod` task for uglifying
- [x] Add `build-watch` task for watching sourced files
- [x] Provide user-friendly bundling command ( use global [gulp-cli](https://github.com/gulpjs/gulp-cli) )
- [x] Write docs
- [ ] Try including `google-maps` in bundle as well (see #151)

**Comment by doomsayer2** [comment]
**NOTE:
Run `npm install` after latest pull**

**Comment by josephmiclaus** [comment]
@doomsayer2 thanks !

**NOTE** that semicolons are not required here :)
