### ISSUE TITLE
Non-default Mobiduls not working anymore

### ISSUE THREAD

**Issue by josephmiclaus** [fhstp-mfg/mobilot#122]
I just tested the Mobidul [brckeberdiebundesstr](https://www.mobilot.at/#/brckeberdiebundesstr) and it didn't work.
This would have been really **important**!!

Here's also a screenshot from some errors:

<img width="895" alt="screen shot 2016-09-29 at 17 03 49" src="https://cloud.githubusercontent.com/assets/4658706/18959519/c78519d8-8666-11e6-8234-0d1937d13d50.png">

<img width="672" alt="screen shot 2016-09-29 at 17 04 07" src="https://cloud.githubusercontent.com/assets/4658706/18959525/cc7c0d48-8666-11e6-8a73-5d83194e3424.png">

It doesn't load the stations, instead it throws an error for each one:

<img width="896" alt="screen shot 2016-09-29 at 17 04 14" src="https://cloud.githubusercontent.com/assets/4658706/18959546/dade461c-8666-11e6-8ae9-dbeb9f887416.png">

**Comment by abisz** [comment]
Fixed, the problem was old mobiduls that didn't have a "mode". I implemented a fallback, but the cleaner solution would be to update the old db entries.

**Comment by josephmiclaus** [comment]
Awesome thanks ! I'll have a look :)
