### ISSUE TITLE
Upload picture not working (on mobile)

### ISSUE THREAD

**Issue by josephmiclaus** [fhstp-mfg/mobilot#124]
Does any of you know why this might be ?

**Comment by abisz** [comment]
@miclaus doesn't work at all or in a specific context (html-container or photo-upload component)?
I don't know how to test this - so I'm not sure how to help...

**Comment by josephmiclaus** [comment]
@abisz yes it is hard to test. I thought you might know what the issue could be. :)

I pinned https://www.mobilot.at to my iOS homescreen and uploaded a photo and it did work seamlessly. So it seems that issue might be _nativ related_. 

My first guess would be that it uses a wrong **picture path**.

**Comment by josephmiclaus** [comment]
It seems that some paths are indeed troubled:

![screen shot 2016-10-17 at 11 45 17](https://cloud.githubusercontent.com/assets/4658706/19433012/485fa572-945f-11e6-975e-338e534725d4.png)

**Comment by josephmiclaus** [comment]
Uploading has been fixed, however displaying the images on mobiles still doesn't work.
