### ISSUE TITLE
Fallback Code Directive for GPS doesn't work

### ISSUE THREAD

**Issue by abisz** [fhstp-mfg/mobilot#138]
Trying to active a station with the fallback code doesn't work.
Tested for this [station](https://www.mobilot.at/#/norbert1/rodelwiese2).
Macbook, Google Chrome (54) 

<img width="672" alt="bildschirmfoto 2016-11-21 um 12 57 50" src="https://cloud.githubusercontent.com/assets/7287780/20481982/405b8700-afea-11e6-8781-95563e005922.png">

**Comment by doomsayer2** [comment]
Fixed for all directives.
