### ISSUE TITLE
Update Setup-Wiki Page 

### ISSUE THREAD

**Issue by kblumenstein** [fhstp-mfg/mobilot#144]
Update the Setup-Wiki Page with the requirements, which has to be installed before run the setup.

**Comment by josephmiclaus** [comment]
@kblumenstein I improved the `setup.sh` script and added **node & npm** and **bower** as a requirements. Was there some other requirement you thought of ?

**Comment by kblumenstein** [comment]
@miclaus composer has to be installed, maybe also the information, because of laravel 4.2 - PHP 5.6. In my case, problems were not correctly installed composer and PHP 5.3
