### ISSUE TITLE
CHECK please: New station always hidden state

### ISSUE THREAD

**Issue by doomsayer2** [fhstp-mfg/mobilot#149]
I dunno if it's only on my side or not, but every new station created is in state `HIDDEN`, if you view it in the `StationController`, where the `renderJSON()` get's called. 
I dunno if it's due to recent changes or my fault but please check if it happens for you too on the last commits. I can't seem to find it, though if found the problem

**Comment by josephmiclaus** [comment]
i'll have a look on occasion.

**Comment by doomsayer2** [comment]
Yeah would be great i dunno if the state is somewhere saved but also in the content in the database nothing apperas. But the Function of `RallyService.getStatus(station.order)` always delivers the hidden state.
