### ISSUE TITLE
Create Mobiuser and login button

### ISSUE THREAD

**Issue by doomsayer2** [fhstp-mfg/mobilot#156]
Additionally remove all mobiduls in category "Near" and "All" that belong to the mobiuser account.

**Require help:**
Currently dealing with the 2 functions that show the mobiduls on Backend in `WebServicesController.php`. The `GetNewestMobiduls()` and `MobidulNearMe()`, but there are different database querys. Basically the Mobiduls which belong to "mobiuser" have to be excluded.

**Comment by doomsayer2** [comment]
Fixed the button and added mobiuser, but currently struggling with the mobiduls to show for him.

**Comment by josephmiclaus** [comment]
- [x] Don't show `mobiuser`'s mobiduls publicly on Home view
