### ISSUE TITLE
Fix view content top styling considering iOS

### ISSUE THREAD

**Issue by josephmiclaus** [fhstp-mfg/mobilot#20]
- [x] Home
- [x] Profil
- [x] Map
- [x] Station List
- [x] Station
- [x] Station Creator
- [x] MobidulOptionen

**Comment by josephmiclaus** [comment]
**View Content** top styling for different views and wrappers not fixed.
Also there are a lot of scrolling issues.

**Comment by abisz** [comment]
@miclaus The additional margin-top for .search-field on homescreen doesn't look very good. is it necessary for iOS?

**Comment by josephmiclaus** [comment]
@abisz please note, that when you change the width of the browser, some angular-material elements also change their height, such as the header toolbar. 

Since the search field is positioned fixed, it doesn't take this change in consideration. Anyhow, it should look good on mobile.

**Comment by abisz** [comment]
I removed the margin-top for big screens (> 1000px) and adapted the offset of the body accordingly.

**Comment by josephmiclaus** [comment]
@abisz Reopened since the iPhone 5 resolutions cuts too much of the header:

![header-height-problem](https://cloud.githubusercontent.com/assets/4658706/18204622/0a14e4c6-711e-11e6-8873-4df0091e8759.jpg)

**Comment by abisz** [comment]
@miclaus can you add a css class to the body depending on the OS for some individual styling?

**Comment by josephmiclaus** [comment]
@abisz yes there are a few variables like `isMobile` and `isIos` under `mobile_imports.js` which could be used. 

however i think media queries might be better here ? 
EDIT: angular-material has some extra options here:
https://material.angularjs.org/latest/layout/options

**Comment by josephmiclaus** [comment]
@abisz i'm at this right now, just a small question, since I cannot find the commit. 

> I removed the margin-top for big screens (> 1000px) and adapted the offset of the body accordingly.

Did you remove the marginTop in `angular.html` ?

**Comment by abisz** [comment]
margin-top from what? But I don't think so

**Comment by josephmiclaus** [comment]
@abisz you wrote that here: https://github.com/fhstp-mfg/mobilot/issues/20#issuecomment-243530978

EDIT: but thiss no thang, i'm at it. :)

**Comment by abisz** [comment]
well here's the commit https://github.com/fhstp-mfg/mobilot/commit/c39706c616a44282c8caaf108c37a29be4e9a7f6
Actually all i did was adding a height property to `md-toolbar,  .md-toolbar-tools`
The media query I wrote in this commit was already removed because it wasn't working on another view

**Comment by josephmiclaus** [comment]
@abisz okay thanks !
