### ISSUE TITLE
Add PhotoUpload as Station Component

### ISSUE THREAD

**Issue by abisz** [fhstp-mfg/mobilot#22]
- [x] Upload and save picture
- [x] Trigger success event
- [x] Event logging with picture, user id (see #5) and componentId
- [x] Export all pictures

**Comment by abisz** [comment]
waiting for #5

**Comment by josephmiclaus** [comment]
@abisz Event logging with picture and user id now possible, see https://github.com/fhstp-mfg/mobilot/issues/5#issuecomment-232754970.

**Comment by abisz** [comment]
@miclaus what do we log as userId if there is no authenticated user? 
`Auth::id()` returns `null` if user is not logged in

**Comment by josephmiclaus** [comment]
@abisz actually a non-authenticated user shouldn't be able to create a station.

I found this piece of code in the `UserController`, which might have some useful data if `Auth::id()` returns `null`:

``` php
$sessionId = Session::getId();
$guest = User::where('username', $sessionId)->first();
// ...
$user = User::getCurrentUser();
// ...
$mobidul = User2Mobidul::where('userId', $guest->id)->get();
```

**Comment by abisz** [comment]
@miclaus but should be able to upload picture with the new station component...
