### ISSUE TITLE
Clone Mobidul

### ISSUE THREAD

**Issue by abisz** [fhstp-mfg/mobilot#23]
**Requirements**:
- [x] Only owner may copy a Mobidul (server side; check for hacking)
- [x] Put copy Mobidul option in Menu under the Admin section
- [x] Copy Mobidul options should only be available for owner
- [x] When Mobidul code is too long, what happens when copying the Mobidul – generate valid Mobidul code
- [x] Correct `navigationitems` for categories in Menu.
- [x] Correct `navigationitems` for stations in Menu.

**Low priority**:
- [x] Before copying the Mobidul, ask for the new Mobidul name (and show new URL)

**Comment by miclaus** [comment]
**Requirements**:
- [ ] Only owner may copy a Mobidul
- [ ] Put copy Mobidul option in Menu under the Admin section
- [ ] Copy Mobidul options should only be available for owner
- [ ] When Mobidul code is too long, what happens when copying the Mobidul

**Low priority**:
- [ ] Before copying the Mobidul, ask for the new Mobidul name (and show new URL)

**Comment by doomsayer2** [comment]
>  When Mobidul code is too long, what happens when copying the Mobidul – generate valid Mobidul code

How is this checked currently? Is it possible with current methods or whats the maximum length of a mobidul name? Is it the 255 varchar. If so it could be checked for that and replaced with a default string if too long.

**Comment by doomsayer2** [comment]
- Clone Category2Station missing.

**Comment by josephmiclaus** [comment]
Still needs checking if mobidulCode is valid + user response.

**Comment by abisz** [comment]
@doomsayer2 I can't save the content of a station that was cloned... any ideas?

**Comment by doomsayer2** [comment]
Fixed it ^^...
Works perfect now ^^... Was a nasty bug I can explain in detail personally. Is related to the backend.

**Comment by josephmiclaus** [comment]
@doomsayer2 nice, very good, thanks !
