### ISSUE TITLE
Log InputCode success activity

### ISSUE THREAD

**Issue by abisz** [fhstp-mfg/mobilot#24]
- [x] Log success and error activity for InputCode
- [x] Save user id
- [x] Save InputCode id

**Comment by abisz** [comment]
waiting for #5

**Comment by josephmiclaus** [comment]
@abisz this should be possible now see https://github.com/fhstp-mfg/mobilot/issues/5#issuecomment-232754970.

**Comment by josephmiclaus** [comment]
@abisz first 2 tasks are done, the InputCode id still has to be saved.

**Comment by josephmiclaus** [comment]
@abisz also don't forget to run `php artisan migrate` it adds the `user` column to the `activity` table.
