### ISSUE TITLE
Clone Station

### ISSUE THREAD

**Issue by abisz** [fhstp-mfg/mobilot#26]
**Requirements**
- [x] Clone Button inside the editor
- [x] After clicking the current station has to be saved
- [x] The view has to change to the new station
- [x] Save station before cloning

**Comment by doomsayer2** [comment]
- Placed a button inside the editor, but don't know where exactly.
- For saving the saveChanges() function will be used.
- Further help is required for other features but cloning works. The function returns the new cloned station id.

**Comment by doomsayer2** [comment]
- Clone Station - jump to new missing.
- Clone Station - save current missing.

**Comment by abisz** [comment]
@doomsayer2 do you also save the station before cloning it? I just thought that would be the expected behaviour

**Comment by miclaus** [comment]
@abisz good point !

**Comment by josephmiclaus** [comment]
@abisz good point !

@doomsayer2 Added "Save station before cloning" requirement.

Should be a simple promise saving the station beforehand and then cloning it as it does atm.

**Comment by doomsayer2** [comment]
@abisz @miclaus I called stationCreator.saveChanges() before cloning the station... So i don't understand what you mean exactly. The current station is cloned only after the previous is saved.

**Comment by doomsayer2** [comment]
- [x]  Make Station Clone button more clear (e.g. grey background) and like the delte button
- [x] Remove "Information" from Station delte
