### ISSUE TITLE
Add TriggerNearBluetooth as Station Component

### ISSUE THREAD

**Issue by josephmiclaus** [fhstp-mfg/mobilot#27]
see https://github.com/fhstp-mfg/mobilot/issues/27#issuecomment-249879088 from @GrischaSchmiedl further below

Steps:
- [x] Intall [petermetz/cordova-plugin-ibeacon](https://github.com/petermetz/cordova-plugin-ibeacon)
- [x] Create Station Component for iBeacon (only when `isCordova`)
  - [x] Opens dialog
  - [x] Waits for iBeacon signal
  - [x] Save iBeacon identifiers

**UPDATE:**

- [x] Add a field to give the found beacon a custom name. For example if one is locked after found, the user should be able to give him a custom name. Like "Turnschuh" or "Auto".
- [x] This should be displayed than on the config and on the final station view, so the user can mark his beacons with the name, handwritten.

- [x] On searching beacons "Near" should unlock the functionality
- [x] At "Far" the, app should say you are near the next station beacon. On "Near" the beacon should fire the event

**Comment by miclaus** [comment]
😄 already posted in description

**Comment by GrischaSchmiedl** [comment]
siehe:
https://github.com/petermetz/cordova-plugin-ibeacon
https://community.estimote.com/hc/en-us/articles/200723678-Can-I-use-Estimote-SDK-with-Xamarin-PhoneGap-other-

**Comment by doomsayer2** [comment]
Update see above.

**Comment by josephmiclaus** [comment]
@doomsayer2 can this be closed ?
