### ISSUE TITLE
[ConfirmSocialPresence] Add Station Component

### ISSUE THREAD

**Issue by abisz** [fhstp-mfg/mobilot#29]
Confirming that two individuals are the same place by scanning QR-Codes vice versa.
- [x] Show QR-Code
- [x] Scan Code from other device
- [x] Trigger Success/Error Action
- [x] Should work in both hybrid and web version (url: station + componentId)
- [ ] Add QR-Code Scanner as Station Component (?)

**Comment by abisz** [comment]
blocked by #44

**Comment by josephmiclaus** [comment]
@abisz this can still be prepared before hybrid is ready.

The web version should show codes instead, right?

**Comment by abisz** [comment]
@miclaus  Codes won't work, because you could use them on your own device. It has to be something that requires another persons device... I don't know how we wanted to do this in web
Of course I can prepare everything, but the main functionality requires a QR Code Reader

**Comment by josephmiclaus** [comment]
@abisz how about the username? (but then users have to necessary be signed up)

i'll take care of the QR Code Reader.

**Comment by abisz** [comment]
Ok the basic setup is done. 
I think I'm going to make a proper qr-code dialog directive next week.

**Comment by abisz** [comment]
@miclaus before I forget: I hardcoded a qr-code code into the mbl-confirm-social directive to test it. that won't work for you, you'll need to create a join-code yourself and replace it for now

**Comment by josephmiclaus** [comment]
@abisz okay thanks ! i also had some problems w/ implementing a qr-code example.

**Comment by kblumenstein** [comment]
It's working, please test it: @miclaus, @abisz, @doomsayer2

- [x] Generates only one code per component
- [x] Shows QR-Code
- [x] Hybrid: Scans QR-Code in station
- [x] Hybrid: Success: show Perform_Action button
- [x] Hybrid: Error, if code is not correct for the current component
- [x] Web: if code is scanned - redirecting to station & show Perform_Action button

**Comment by josephmiclaus** [comment]
@kblumenstein can this be closed ?
