### ISSUE TITLE
Document initial project setup for new developers

### ISSUE THREAD

**Issue by josephmiclaus** [fhstp-mfg/mobilot#3]
- [x] Add `.sh` script for initial setup
- [x] Update `README.md`

**Comment by abisz** [comment]
Developers have to manually create the following folder structure inside 'app/storage' in order for php artisan to work:
- cache
- logs
- meta
- sessions
- views

**Comment by abisz** [comment]
you also need an "upload" folder inside public for uploading media files

**Comment by josephmiclaus** [comment]
Setup process for `.sh` file:
- Run `composer install`
- Create folders (mentioned by @abisz) under `app/storage/`
- Create folders (mentioned by @abisz) under `public/`
- Manually create `database.php` if necessary
- Manually create database named `mobilot` (MySQL)
- Run `php artisan migrate`
