### ISSUE TITLE
Add FreeTextInput as Station Component

### ISSUE THREAD

**Issue by abisz** [fhstp-mfg/mobilot#31]
- [x] Add StationComponent
- [x] Add Configuration Element
- [x] Save User Input in Activity Log
- [x] Export all Texts

**Comment by abisz** [comment]
Should there be an action triggered once the user send an answer? Probably yes, right?

**Comment by josephmiclaus** [comment]
What kind of action do you mean? @abisz 
- an event like `say:Something` or
- a `commitActivity()` action?

**Comment by abisz** [comment]
@miclaus actually both :) we already discussed it during the last sprint meeting!

**Comment by abisz** [comment]
I'll close this for now, the export format has to be discussed. Right now I just return an array with all texts...
