### ISSUE TITLE
Create ActivityService

### ISSUE THREAD

**Issue by josephmiclaus** [fhstp-mfg/mobilot#5]
The `ActivityService` should be a customizable service for logging **user actions** and **app events** to the server. This is specifically thought for data, which otherwise would be hard to capture and analyse for future improvements (e.g. performance improvements and debugging).

Initially the service should be implemented for the following:
- [x] Geolocation events (`success`, `error`), to check whether Geolocation events are executed correctly

**Backlog**
- [ ] User position data, to improve `TriggerNear` directive and other Geolocation related functionality
- [x] Log picture and user id of uploader (see #22)
- [x] Log InputCode success activity when completed (see #24)

**Comment by miclaus** [comment]
- [ ] Rename AnalyticsService to **ActivityLogService**

**Comment by josephmiclaus** [comment]
Renames to **ActivityServices**

**Comment by josephmiclaus** [comment]
### ActivityService
- **commitActivity(activity):boolean** - Commiting an activity object locally to a private activity stack. Returns `true` if everything went okay, returns `false` and throws `Passed an invalid activity object`.
- **pushActivity():Promise** - Pushes the stack of activities to server.

**Activity** object:
An object describing the activity that should be commited locally. The activity object requires the following format:

``` js
var activity = {
  type: ActivityService.TYPES.{ACTIVITY_TYPE},
  name: ActivityService.{ACTIVITY_TYPE}.{ACTIVITY_NAME}
  payload: {
    {ACTIVITY_PAYLOAD}
  }
}
```
- [x] Move this description to docs.

**Comment by josephmiclaus** [comment]
Create Admin view, to easily view Activities (see #32)

This is however planed for [v.0.9.3](https://github.com/fhstp-mfg/mobilot/milestone/1)
