### ISSUE TITLE
renderJSON gets called multiple times on StationView

### ISSUE THREAD

**Issue by abisz** [fhstp-mfg/mobilot#52]

**Comment by josephmiclaus** [comment]
@abisz do you think this is easy to fix? if so, do you think you can fix this maybe? please :)

**Comment by abisz** [comment]
@miclaus no idea, but I can take a look.

**Comment by josephmiclaus** [comment]
@abisz if you have time :) thank you !

**Comment by josephmiclaus** [comment]
very cool ! thank you !
