### ISSUE TITLE
Reposition StationComponent info button

### ISSUE THREAD

**Issue by josephmiclaus** [fhstp-mfg/mobilot#62]
We should reposition the StationComponent info button, since it takes up quite some space and the WYSIWYG editor for example, doesn't fit anymore.:

Any volunteers? 😄 

Screenshot taken on iPhone 5s:

![img_1235](https://cloud.githubusercontent.com/assets/4658706/17363803/ed496b54-597c-11e6-940b-3902442fe1d8.PNG)

**Comment by abisz** [comment]
I'll do it!

**Comment by josephmiclaus** [comment]
@abisz thank you 😃

**Comment by abisz** [comment]
Done! but we should redesign the editor anyway!
