### ISSUE TITLE
Complete release v1.0

### ISSUE THREAD

**Issue by abisz** [fhstp-mfg/mobilot#81]
Todos:
- [x] Remove not finished features
- [x] Change backend url in cordova
- [x] Add sponsors to README

**Comment by abisz** [comment]
@doomsayer2 did you find the backend connection details for cordova so we can change the?

**Comment by josephmiclaus** [comment]
@abisz @doomsayer2 Use `copyToLiveServer.sh` (after backing up files and db) then simply change the `_live` var in `constants.js` to true. Although it would be better to have a fixed vars file, which doesn't have to be changed on every new live version. 

This could be put into a file (e.g. `fixed_vars.js`), which gets copied once, then the `copyToLiveServer.sh` should be updated to ignore the fixed vars file.

**Comment by josephmiclaus** [comment]
@abisz @doomsayer2 okay so i broke the live version ... i'll fix this later today !

**Comment by abisz** [comment]
@miclaus What did you (try to) do?

**Comment by josephmiclaus** [comment]
@abisz i tried to move the live version from `/var/www/mobilot.at/mobilot/public` to the parent dir.

i think i might have deleted some dotfiles ..

**Comment by kblumenstein** [comment]
Please fix it as soon as possible. Yesterday, our financier got this address with the information, that the newest version is available!

**Comment by miclaus** [comment]
@abisz i tried to move the live version from `/var/www/mobilot.at/mobilot/public` to the parent dir.

i think i might have deleted some dotfiles ..

**Comment by josephmiclaus** [comment]
@abisz @doomsayer2 where are our backups ? could you please write this on slack ? thank you :)

**Comment by josephmiclaus** [comment]
@abisz @kblumenstein : should be working again . 

the live version is now under `/var/www/mobilot.at/mobilot`

**Comment by josephmiclaus** [comment]
closing this
