### ISSUE TITLE
Error Dialog on Position determination

### ISSUE THREAD

**Issue by doomsayer2** [fhstp-mfg/mobilot#96]
- [x] Change the frequent occurence of the error Dialog in MapController.js if the position can't be acquired. 
- [x] Also check why the Mobidul menu is not shown fully if the dialog is shown.
- [ ] Check the MapService.js and why its continiously logging "No gathering position interval promise defined.", when in the web.

**Comment by josephmiclaus** [comment]
I believe this dialog doesn't exist anymore.

The console error should be part of a separate issue, if still occurring.

Closing this.
